import { exportToExcel, exportToDocx } from './export-utils';

describe('Document Export Utilities (Excel & Word)', () => {
  const mockAnchor = {
    href: '',
    download: '',
    click: jest.fn(),
  };

  beforeAll(() => {
    // Setup Node global mocks for browser DOM APIs
    (global as any).document = {
      createElement: jest.fn(() => mockAnchor),
      body: {
        appendChild: jest.fn(),
        removeChild: jest.fn(),
      },
    };
    (global as any).URL = {
      createObjectURL: jest.fn(() => 'blob:mock-url'),
      revokeObjectURL: jest.fn(),
    };
  });

  describe('exportToExcel', () => {
    it('is callable and validates export options without throwing errors', () => {
      expect(() => {
        exportToExcel({
          filename: 'Test_Export',
          sheetName: 'TestSheet',
          title: 'Unit Test Export',
          subtitle: 'Subtitle for test',
          metadata: { 'Generated By': 'Jest Test Suite' },
          headers: ['ID', 'Name', 'Role'],
          rows: [
            ['1', 'Test User', 'Admin'],
            ['2', null, undefined],
          ],
        });
      }).not.toThrow();
    });
  });

  describe('exportToDocx', () => {
    it('is callable and compiles sections into valid word document blob', async () => {
      await expect(
        exportToDocx({
          filename: 'Test_Docx_Dossier',
          title: 'Automated Audit Dossier',
          subtitle: 'Unit test verification',
          branch: 'Coimbatore',
          staffName: 'QA Engineer',
          staffRole: 'TESTER',
          sections: [
            {
              heading: '1. Executive Performance',
              description: 'Section description text',
              table: {
                headers: ['Metric', 'Score'],
                rows: [['Compliance', '100%']],
                columnWidthsPercentage: [50, 50],
              },
              bullets: ['Bullet item 1', 'Bullet item 2'],
            },
          ],
        })
      ).resolves.not.toThrow();
    });
  });
});
